name: alfresco-identity-service
version: 2.0.0
appVersion: 1.2.0
description: The Alfresco Identity Service will become the central component responsible for identity-related capabilities needed by other Alfresco software, such as managing users, groups, roles, profiles, and authentication. Currently it deals just with authentication.
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
keywords:
  - alfresco
  - keycloak
  - identity-service
home: https://github.com/Alfresco/alfresco-identity-service/tree/master/helm
sources:
  - https://github.com/Alfresco/alfresco-identity-service/tree/master/helm
maintainers:
  - name: Alfresco
